name: MenzelUI-Paper
version: ${version}
main: de.menzel.menzelUI.paper.MenzelUIPaper
api-version: "1.21"
author: Kolja Menzel
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
commands:
  mui:
    description: Reloads the MenzelUI Paper config
    usage: /mui reload
    permission: mui.command.reload
permissions:
  mui.command.reload:
    description: Allows reloading the MenzelUI Paper config
    default: op
